#!/bin/bash

# run the demo even if eclipse is unavailable 

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
PYTHONPATH=$PYTHONPATH:$DIR/mininet
PYTHONPATH=$PYTHONPATH:$DIR/pox
PYTHONPATH=$PYTHONPATH:$DIR/our_controller
PYTHONPATH=$PYTHONPATH:$DIR/orchestrator
PYTHONPATH=$PYTHONPATH:$DIR/Unify_ncclient
export PYTHONPATH

killall netconfd controller click
rm -f /tmp/ncxserver*
mn -c
for i in {1..30}; do ip link del uny_$i; done

#python gui-demo.py --nf-topo nf-comp-decomp-op.mn --phy-topo phy-4netconf.mn
#python gui-demo.py --nf-topo review-ewsdn-nf.mn --phy-topo phy-3netconf.mn
#python gui-demo.py --nf-topo review-ewsdn-nf.mn --phy-topo review-ewsdn-phy.mn
#python gui-demo.py --nf-topo review-ewsdn-nf.mn --phy-topo review-sigcomm1-phy.mn
python gui-demo.py
